version: "3.9"

services:
  api:
    build: .
    ports:
      - "8090:8000"
    environment:
      DB_HOST: db
      POSTGRES_DB: labdb
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
